import { Filter } from '../models/reusable-filter.model';

export const memberTimeStampFilters = ['createdAt'];

export const memberFilters: Filter[] = [
  {
    type: 'autoComplete',
    name: 'name',
    label: 'member.name',
    isSet: false,
  },
  {
    type: 'string',
    name: 'address',
    label: 'member.address',
    isSet: false,
  },
  {
    type: 'autoComplete',
    name: 'district',
    label: 'member.district',
    isSet: false,
  },
  {
    type: 'selection',
    name: 'city',
    label: 'member.city',
    options: [
      { name: 'London', value: 'London' },
      { name: 'Manchester', value: 'Manchester' },
      { name: 'Birmingham', value: 'Birmingham' },
      { name: 'Leeds', value: 'Leeds' },
      { name: 'Liverpool', value: 'Liverpool' },
      { name: 'Newcastle', value: 'Newcastle' },
      { name: 'Nottingham', value: 'Nottingham' },
      { name: 'Sheffield', value: 'Sheffield' },
      { name: 'Bristol', value: 'Bristol' },
      { name: 'Leicester', value: 'Leicester' },
      { name: 'Brighton', value: 'Brighton' },
      { name: 'Plymouth', value: 'Plymouth' },
      { name: 'Stoke-on-Trent', value: 'Stoke-on-Trent' },
      { name: 'Wolverhampton', value: 'Wolverhampton' },
      { name: 'Derby', value: 'Derby' },
      { name: 'Sunderland', value: 'Sunderland' },
      { name: 'Southampton', value: 'Southampton' },
      { name: 'Portsmouth', value: 'Portsmouth' },
      { name: 'York', value: 'York' },
      { name: 'Reading', value: 'Reading' },
      { name: 'Cambridge', value: 'Cambridge' },
      { name: 'Oxford', value: 'Oxford' },
      { name: 'Norwich', value: 'Norwich' },
      { name: 'Exeter', value: 'Exeter' },
      { name: 'Lancaster', value: 'Lancaster' },
    ],
    isSet: false,
  },
  {
    type: 'time',
    name: 'createdAt',
    label: 'member.createdAt',
    options: [
      { name: 'filterMenu.before', value: 'max' },
      { name: 'filterMenu.after', value: 'min' },
      { name: 'filterMenu.at', value: 'minMax' },
      { name: 'filterMenu.between', value: 'between' },
    ],
    isSet: false,
  },
];

export const mockDisctrict: string[] = [
  'Camden',
  'City of London',
  'Kensington and Chelsea',
  'Islington',
  'Southwark',
  'Westminster',
  'Birmingham',
  'Leeds',
  'Liverpool',
  'Manchester',
  'Bristol',
  'Sheffield',
  'Leicester',
  'Bradford',
  'Coventry',
  'Kingston upon Hull',
  'Newcastle upon Tyne',
  'Stoke-on-Trent',
  'Wolverhampton',
  'Derby',
  'Sunderland',
  'Brighton and Hove',
  'Plymouth',
  'Portsmouth',
  'York',
];

export const mockName: string[] = [
  'John Smith',
  'Amelia Jones',
  'Isla Taylor',
  'Oliver Brown',
  'Emily Williams',
  'Ava Wilson',
  'George Johnson',
  'Arthur Davies',
  'Noah Patel',
  'Sophie Wright',
  'Grace Robinson',
  'Mia Thompson',
  'Lily White',
  'Freya Hughes',
  'Lucas Edwards',
];
